name: 'nhanes_project'
version: '1.0.0'
config-version: 2

profile: 'nhanes_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  nhanes_project:
    +materialized: view